/* Generated by Yosys 0.8+498 (git sha1 92dde319f, gcc 13.3.0-6ubuntu2~24.04.1 -fPIC -Os) */

module top(y, w);
  wire _0_;
  wire _1_;
  input [2:0] w;
  output y;
  assign _1_ = w[0] | w[1];
  assign _0_ = _1_ | w[2];
  assign y = ~_0_;
endmodule
