/* Generated by Yosys 0.8+618 (git sha1 acd8bc0a7, gcc 13.3.0-6ubuntu2~24.04.1 -fPIC -Os) */

module top(y, clk, sel);
  input clk;
  wire reg_assign;
  wire [1:0] reg_count;
  input sel;
  output y;
  assign reg_assign = 1'h0;
  assign reg_count = 2'h0;
  assign y = 1'h0;
endmodule
