/* Generated by Yosys 0.8+506 (git sha1 349c47250, gcc 13.3.0-6ubuntu2~24.04.1 -fPIC -Os) */

module top(y, w);
  wire [2:0] _0_;
  wire _1_;
  input [2:0] w;
  output y;
  assign _0_[2] = w[1] ^ w[0];
  assign _1_ = w[0] | _0_[2];
  assign y = ~_1_;
  assign _0_[1:0] = { w[0], 1'h0 };
endmodule
