/* Generated by Yosys 0.8+634 (git sha1 39f4c1096, gcc 13.3.0-6ubuntu2~24.04.1 -fPIC -Os) */

module top(y, clk, sel);
  input clk;
  reg reg_assign = 1'h0;
  wire [1:0] reg_count;
  input sel;
  output y;
  always @(posedge clk)
      reg_assign <= sel;
  assign reg_count = 2'h0;
  assign y = reg_assign;
endmodule
