/* Generated by Yosys 0.9+932 (git sha1 0466c4853, gcc 13.3.0-6ubuntu2~24.04.1 -fPIC -Os) */

module top(y, clk, w);
  input clk;
  wire [1:0] i;
  input w;
  output y;
  reg y = 1'h0;
  always @(posedge clk)
      y <= 1'h1;
  assign i = 2'h0;
endmodule
