/* Generated by Yosys 0.8+416 (git sha1 b37c31e2c, gcc 13.3.0-6ubuntu2~24.04.1 -fPIC -Os) */

module top(y, clk, wire1);
  input clk;
  wire [1:0] reg1;
  wire [1:0] reg2;
  input [1:0] wire1;
  output [1:0] y;
  reg \reg2_reg[0]  = 1'h0;
  always @(posedge clk)
      \reg2_reg[0]  <= 1'h1;
  assign reg2[0] = \reg2_reg[0] ;
  assign reg1 = 2'b0x;
  assign reg2[1] = 1'h0;
  assign y = { 1'h0, reg2[0] };
endmodule
