/* Generated by Yosys 0.9 (git sha1 1979e0b1f, gcc 13.3.0-6ubuntu2~24.04.1 -fPIC -Os) */

module top(y, clk);
  input clk;
  wire [5:0] reg1;
  wire [8:0] reg2;
  output y;
  reg \reg2_reg[0]  = 1'h0;
  always @(posedge clk)
      \reg2_reg[0]  <= 1'h1;
  assign reg2[0] = \reg2_reg[0] ;
  assign reg1 = 6'h00;
  assign reg2[8:1] = 8'h00;
  assign y = reg2[0];
endmodule
