/* Generated by Yosys 0.9+932 (git sha1 4b18a4528, gcc 13.3.0-6ubuntu2~24.04.1 -fPIC -Os) */

module top(y, clk);
  input clk;
  wire [5:0] reg1;
  wire [8:0] reg2;
  output y;
  assign reg1 = 6'h00;
  assign reg2 = 9'h000;
  assign y = 1'h0;
endmodule
